### PR TITLE
28 fix scroll position issue

### LINKED ISSUE #28: Fix scroll position issue
https://stackoverflow.com/questions/36904185/react-router-scroll-to-top-on-every-transition

### PR DESCRIPTION
**Pull request by Ralvgar**
Solved

### CODE REVIEW

File: src/App.js [hunk 1]
```diff
@@ -2,16 +2,19 @@ import React from 'react';
...
 import History from './screens/History/History';
+import { ScrollToTop } from '../src/components/ScrollToTop/ScrollToTop';
 import "./index.scss";
 
 function App() {
   return (
     <HashRouter>
       <Switch>
         <Route path='/History'>
+          <ScrollToTop />
```
Comment (albertvazquezm) [inline src/App.js]: Well done! However, I recommend you wrapping the View components (Main, History) instead of adding yours before.

<ScrollToTop><Main/></ScrollToTop>

This will help identifying that it has been included here for that route.

Comment (Ralvgar) [reply src/App.js]: I think that it does'nt work.

**Review by albertvazquezm — APPROVED** [review]
